name: Ward_metrics_computation

on:
  workflow_dispatch: 
  schedule:
    - cron:  '0 10 * * *'

jobs:
  setup_run_r:
    runs-on: ubuntu-18.04

    steps:
      - name: Check out this repo
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
         version: '290.0.1'
         service_account_key: ${{ secrets.GCP_SA_KEY }}
         service_account_email: ${{ secrets.GCP_SA_EMAIL }}
         export_default_credentials: true
      - run: gcloud info
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install Python dependencies
        run: |
          pip install pandas gspread  numpy luigi          
      - name: Run py script
        run: |
          python pipeline/pipeline/ward_metrics.py